# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Asia/Shanghai

# jekyll-seo-tag settings
title: Chirpy
tagline: A text-focused Jekyll theme
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Fill in the protocol & hostname for your site.
url: "https://do-hyun123.github.io"

github:
  username: do-hyun123 # change to your GitHub username

twitter:
  username: twitter_username # change to your Twitter username (if any)

social:
  name: Do Hyun
  email: shickcoong777@gmail.com # change to your email address
  links:
    - https://twitter.com/username # change to your Twitter homepage
    - https://github.com/do-hyun123 # change to your GitHub homepage

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:

# Pageviews settings
pageviews:
  provider:

# Prefer color scheme setting.
theme_mode:

# The CDN endpoint for media resources.
cdn: "https://chirpy-img.netlify.app"

# the avatar on sidebar, support local or CORS resources
avatar: "/commons/avatar.jpg"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image:

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: disqus
  disqus:
    shortname: do-hyun

# Self-hosted static assets, optional
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
